### ISSUE TITLE
What is different compared to flake8-implicit-str-concat?

### ISSUE THREAD

**Issue by MartinThoma** [10sr/flake8-no-implicit-concat#18]
It seems to do pretty much the same. Could you please point out the differences, except for the name?

**Comment by 10sr** [comment]
README already describes the difference!
https://github.com/10sr/flake8-no-implicit-concat#other-plugins--linters

 > There are cases where this plugin prefers to implicit concatenation over explicit + operator , so these two plugins cannot be used in combination.

For example, flake8-implicit-str-concat prefers:

```python
a = ("abc"
     "def")
```

over:

```python
a = ("abc" +
     "def")
```

where this plugin likes the latter.

**Comment by MartinThoma** [comment]
Thank you for the example!
